In [49]:
import numpy as np
import networkx as nx
from pyvis.network import Network
import matplotlib.pyplot as plt
import matplotlib.cm as cm

In [116]:
class address:
    
    def __init__(self, coins, public):
        
        self.public = public
        self.coins = coins
       
    def receive(self, amount):
        self.coins += amount
        
    def send(self, other, amount):
        
        if(self.coins >= amount):
            other.receive(amount)
            self.coins -= amount
            amount_sent = amount
        else:
            
            other.receive(self.coins)
            self.coins = 0
            amount_sent = self.coins 
            
        return amount_sent

    
class blockchain:
    
    
    def __init__(self, size, coins, num_shops):
        
        self.num_shops = num_shops
        self.network = np.zeros((size, size))
        self.addresses = []
        for i in range(size):
            self.addresses.append(address(coins, i))
            
    def update_network(self, address_send, address_receive, amount):
        self.network[address_send][address_receive] += amount
    
    def print_ledger(self):
        
        for address in self.addresses:
            print("amount: " + str(address.coins) + " id:" + str(address.public))
            
    def execute_transactions(self, addresses_to_send):
        for i, address in enumerate(self.addresses):
            if(addresses_to_send[i] != i and i > self.num_shops -1):
                amount_sent = address.send(self.addresses[addresses_to_send[i]], 1)
                self.update_network(i, addresses_to_send[i], amount_sent)

class simulation:
    
    def __init__(self, size, coins, num_shops):
        self.blockchain_size = size
        self.blockchain  = blockchain(size, coins, num_shops)
        self.num_shops = num_shops
        
    def step(self):
        probabilities = []
        for i in range(self.blockchain_size):
            if(i < self.num_shops):
                probabilities.append(1/self.blockchain_size * 3)
            else:
                probabilities.append((1 - (1/self.blockchain_size * 3) * self.num_shops)/ (self.blockchain_size - self.num_shops))
                
        addresses_to_send = np.random.choice(self.blockchain_size, self.blockchain_size, probabilities) 
        self.blockchain.execute_transactions(addresses_to_send)
    
    def simulate(self, number_of_steps):
        
        for i in range(number_of_steps):
            self.step()
    
    def print_ledger(self):
        self.blockchain.print_ledger()
        
            

In [122]:
world = simulation(10, 1, 2)
world.simulate(50)
world.print_ledger()
network = world.blockchain.network
print(network)

amount: 4 id:0
amount: 6 id:1
amount: 0 id:2
amount: 0 id:3
amount: 0 id:4
amount: 0 id:5
amount: 0 id:6
amount: 0 id:7
amount: 0 id:8
amount: 0 id:9
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1. 1. 0. 0. 0.]
 [1. 2. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 3. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


In [123]:
G = nx.from_numpy_matrix(network, create_using=nx.DiGraph)
net = Network(notebook = True)
net.from_nx(G)
net.show("example.html")



In [98]:
path = "test.txt"
nx.write_edgelist(G, path, delimiter=' ', comments='#', encoding='utf-8', data = False)

In [7]:
tree_matrix =  np.array([[0, 1, 1, 0, 0, 0, 0],
                         [1, 0, 0, 1, 1, 0, 0],
                         [1, 0, 0, 0, 0, 1, 1], 
                         [0, 1, 0, 0, 0, 0, 0], 
                         [0, 1, 0, 0, 0, 0, 0],
                         [0, 0, 1, 0, 0, 0, 0],
                         [0, 0, 1, 0, 0, 0, 0]])

G = nx.from_numpy_matrix(tree_matrix, create_using=nx.DiGraph)
net = Network(notebook = True)
net.from_nx(G)
net.show("example.html")